### ISSUE TITLE
Find wand issue

### ISSUE THREAD

**Issue by BranTechnology** [GammaGames/kano_wand#7]
Hello I have the hue.pay file just looking for the wand copying exactly the same code from your blog and it worked the first time it discovered the wand but today I woke up to continue coding it and now it gives me a strange error when I try to locate the wand even when I use the same code as yesterday I'll post a picture of the error below any help would be much appreciated thanks 
![image](https://user-images.githubusercontent.com/124531972/216860857-a92b86f4-0ec6-4aca-a519-d9b76c20c0a5.jpeg)

**Comment by GammaGames** [comment]
Was the closing an accident? I'm not sure what the issue is, but I was thinking about digging out my wand to try to recreate it
